export const PRODUCTS = [
  { 
    id: 1, 
    name: "Midnight Onyx", 
    category: "Coffee", 
    basePrice: 24, 
    originalPrice: 32,
    inStock: true,
    rating: 4.9, 
    notes: "Dark Chocolate, Molasses, Smoke",
    description: "Our signature dark roast. Sourced high in the volcanic regions of Sumatra, the Midnight Onyx is roasted past the second crack to draw out intense, smoky flavors with a rich, syrupy body. Perfect for a bold espresso or a life-affirming French Press.",
    origin: "Sumatra, Indonesia",
    altitude: "1,400m - 1,800m",
    process: "Wet-Hulled",
    stats: { acidity: 2, body: 5, sweetness: 3 , complexity: 4, finish: 5 },
    serve: {"vessel":"French Press","grind":"Coarse","temp":"95°C","time":"4:00 Min"}
  },
  { 
    id: 2, 
    name: "Ethiopian Yirgacheffe", 
    category: "Coffee", 
    basePrice: 28, 
    inStock: true,
    rating: 4.8, 
    notes: "Jasmine, Lemon, Bergamot",
    description: "A delicate, tea-like coffee from the birthplace of Arabica. This washed Yirgacheffe bursts with vibrant floral aromas and a crisp, citrusy acidity. It's a bright, elegant cup best enjoyed as a pour-over.",
    origin: "Yirgacheffe, Ethiopia",
    altitude: "1,900m - 2,200m",
    process: "Washed",
    stats: { acidity: 5, body: 2, sweetness: 4 , complexity: 5, finish: 4 },
    serve: {"vessel":"Pour Over (V60)","grind":"Medium-Fine","temp":"92°C","time":"3:00 Min"}
  },
  { 
    id: 3, 
    name: "Colombian Supremo", 
    category: "Coffee", 
    basePrice: 22, 
    originalPrice: 30,
    inStock: true,
    rating: 4.7, 
    notes: "Caramel, Apple, Sweet",
    description: "The classic crowd-pleaser. Grown in the pristine Andes mountains, this Supremo lot offers a perfectly balanced cup with a smooth caramel sweetness and a hint of crisp green apple acidity. Highly versatile.",
    origin: "Huila, Colombia",
    altitude: "1,500m - 1,900m",
    process: "Washed",
    stats: { acidity: 3, body: 3, sweetness: 4 , complexity: 3, finish: 3 },
    serve: {"vessel":"Aeropress","grind":"Medium","temp":"90°C","time":"2:00 Min"}
  },
  { 
    id: 4, 
    name: "Guatemalan Antigua", 
    category: "Coffee", 
    basePrice: 25, 
    inStock: false,
    rating: 4.6, 
    notes: "Cocoa, Spices, Orange",
    description: "Cultivated in a valley surrounded by three volcanoes, this Antigua coffee is complex and deeply rewarding. Look for a velvety texture, rich baking cocoa, and a subtle, zesty orange finish.",
    origin: "Antigua, Guatemala",
    altitude: "1,300m - 1,600m",
    process: "Washed",
    stats: { acidity: 3, body: 4, sweetness: 3 , complexity: 4, finish: 4 },
    serve: {"vessel":"Pour Over (Chemex)","grind":"Medium-Coarse","temp":"93°C","time":"4:30 Min"}
  },
  { 
    id: 5, 
    name: "Sumatra Mandheling", 
    category: "Coffee", 
    basePrice: 26, 
    originalPrice: 35,
    inStock: true,
    rating: 4.8, 
    notes: "Earthy, Herbal, Cedar",
    description: "A wild, untamed profile. The traditional wet-hulling process gives this Mandheling its signature earthy, cedar-like aroma and an incredibly heavy, satisfying mouthfeel. Low acidity, high impact.",
    origin: "Batak Region, Sumatra",
    altitude: "1,100m - 1,500m",
    process: "Wet-Hulled",
    stats: { acidity: 1, body: 5, sweetness: 2 , complexity: 2, finish: 5 },
    serve: {"vessel":"French Press","grind":"Coarse","temp":"96°C","time":"5:00 Min"}
  },
  { 
    id: 6, 
    name: "Kenya AA", 
    category: "Coffee", 
    basePrice: 29, 
    inStock: true,
    rating: 4.9, 
    notes: "Blackberry, Wine, Grapefruit",
    description: "Famous for its intense, wine-like acidity and complex berry flavors. This AA grade (largest bean size) lot from Nyeri is incredibly juicy, with a tart grapefruit finish that lingers beautifully.",
    origin: "Nyeri, Kenya",
    altitude: "1,700m - 1,900m",
    process: "Washed",
    stats: { acidity: 5, body: 3, sweetness: 4 , complexity: 5, finish: 4 },
    serve: {"vessel":"Pour Over (V60)","grind":"Medium-Fine","temp":"91°C","time":"2:45 Min"}
  },
  { 
    id: 7, 
    name: "Costa Rica Tarrazu", 
    category: "Coffee", 
    basePrice: 27, 
    inStock: true,
    rating: 4.7, 
    notes: "Honey, Citrus, Chocolate",
    description: "A brilliantly clean and sweet cup from the renowned Tarrazu region. Notes of warm honey and milk chocolate give way to a sparkling citrus acidity. A phenomenal daily drinker.",
    origin: "Tarrazu, Costa Rica",
    altitude: "1,200m - 1,800m",
    process: "Honey Processed",
    stats: { acidity: 4, body: 3, sweetness: 5 , complexity: 4, finish: 3 },
    serve: {"vessel":"Moka Pot","grind":"Fine","temp":"Boiling","time":"1:30 Min"}
  },
  { 
    id: 8, 
    name: "Brazilian Santos", 
    category: "Coffee", 
    basePrice: 20, 
    originalPrice: 28,
    inStock: true,
    rating: 4.5, 
    notes: "Nutty, Smooth, Low Acidity",
    description: "The backbone of many great espresso blends, this natural processed Brazilian bean is incredibly smooth, low in acidity, and dominated by comforting notes of toasted nuts and chocolate.",
    origin: "Minas Gerais, Brazil",
    altitude: "800m - 1,200m",
    process: "Natural",
    stats: { acidity: 1, body: 4, sweetness: 4 , complexity: 2, finish: 3 },
    serve: {"vessel":"Espresso","grind":"Very Fine","temp":"93°C","time":"30 Sec"}
  },
  { 
    id: 9, 
    name: "Death's Door Espresso", 
    category: "Coffee", 
    basePrice: 32, 
    inStock: true,
    rating: 5.0, 
    notes: "Intense, Cacao Nibs, Bold",
    description: "Not for the faint of heart. This meticulously crafted blend is roasted darker than the night sky. Expect a massive, syrupy body, zero acidity, and intense notes of raw cacao nibs and toasted wood. Cuts through milk effortlessly.",
    origin: "Proprietary Blend",
    altitude: "Various",
    process: "Mixed",
    stats: { acidity: 1, body: 5, sweetness: 1 , complexity: 3, finish: 5 },
    serve: {"vessel":"Espresso","grind":"Very Fine","temp":"94°C","time":"28 Sec"}
  },
  // --- TEA ---
  { 
    id: 10, 
    name: "Himalayan Hand-Rolled Oolong", 
    category: "Tea", 
    basePrice: 28, 
    inStock: true,
    rating: 4.9, 
    notes: "Orchid, Honey, Stone Fruit",
    description: "Plucked in the misty altitudes of Darjeeling, this rare oolong is carefully hand-rolled to preserve the whole leaf. It unfurls gracefully in your cup, offering a fragrant, floral infusion that can be steeped multiple times.",
    origin: "Darjeeling, India",
    altitude: "2,000m",
    process: "Oxidized",
    stats: { acidity: 2, body: 3, sweetness: 4 , complexity: 5, finish: 4 },
    serve: {"vessel":"Gaiwan","grind":"Whole Leaf","temp":"85°C","time":"45 Sec"}
  },
  { 
    id: 11, 
    name: "Imperial Matcha Grade A", 
    category: "Tea", 
    basePrice: 45, 
    originalPrice: 60,
    inStock: true,
    rating: 5.0, 
    notes: "Umami, Sweet Grass, Creamy",
    description: "Sourced directly from Uji, Japan, these shade-grown leaves are stone-ground into a vibrantly green, ultrafine powder. Whisk it into a frothy, energizing elixir characterized by a deep umami flavor and zero bitterness.",
    origin: "Uji, Japan",
    altitude: "Sea Level",
    process: "Stone-Ground",
    stats: { acidity: 1, body: 5, sweetness: 3 , complexity: 4, finish: 5 },
    serve: {"vessel":"Chawan (Bowl)","grind":"Powder","temp":"80°C","time":"1:30 Min"}
  },
  { 
    id: 12, 
    name: "Silver Needle White Tea", 
    category: "Tea", 
    basePrice: 35, 
    inStock: true,
    rating: 4.8, 
    notes: "Melon, Honeysuckle, Crisp",
    description: "Composed entirely of unopened leaf buds covered in silvery down, this delicate tea is minimally processed. The resulting brew is exceptionally light, crisp, and naturally sweet, perfect for moments of calm.",
    origin: "Fujian, China",
    altitude: "800m",
    process: "Sun-Dried",
    stats: { acidity: 1, body: 2, sweetness: 5 , complexity: 3, finish: 3 },
    serve: {"vessel":"Glass Teapot","grind":"Whole Leaf","temp":"75°C","time":"3:00 Min"}
  },
  // --- DRYFRUIT ---
  { 
    id: 13, 
    name: "Jumbo Medjool Dates", 
    category: "Dryfruit", 
    basePrice: 18, 
    inStock: true,
    rating: 4.9, 
    notes: "Caramel, Brown Sugar, Chewy",
    description: "Known as the 'King of Dates', these oversized Medjools are incredibly plump, moist, and carry a rich, caramel-like sweetness. They are an ideal pairing for a stark cup of black coffee or simply a luxurious, energizing snack.",
    origin: "Jordan Valley",
    altitude: "Below Sea Level",
    process: "Sun-Dried",
    stats: { acidity: 1, body: 5, sweetness: 5 , complexity: 4, finish: 5 },
    serve: {"vessel":"N/A","grind":"Whole","temp":"Room Temp","time":"Ready"}
  },
  { 
    id: 14, 
    name: "Roasted Afghan Pistachios", 
    category: "Dryfruit", 
    basePrice: 26, 
    originalPrice: 35,
    inStock: true,
    rating: 4.7, 
    notes: "Salty, Earthy, Crunchy",
    description: "Sourced from high-altitude orchards, these pistachios are smaller but significantly more flavorful than commercial varieties. Delicately dry-roasted with a hint of Himalayan pink salt to enhance their natural buttery profile.",
    origin: "Herat, Afghanistan",
    altitude: "1,200m",
    process: "Dry-Roasted",
    stats: { acidity: 1, body: 4, sweetness: 2 , complexity: 3, finish: 4 },
    serve: {"vessel":"N/A","grind":"Whole","temp":"Room Temp","time":"Ready"}
  },
  { 
    id: 15, 
    name: "Organic Turkish Figs", 
    category: "Dryfruit", 
    basePrice: 22, 
    inStock: true,
    rating: 4.8, 
    notes: "Jammy, Honey, Seed-Crunch",
    description: "Sun-dried to perfection, these organic figs are naturally jammy and incredibly sweet without any added sugars. They offer a delightful textural contrast and pair beautifully with sharp cheeses and a medium roast coffee.",
    origin: "Izmir, Turkey",
    altitude: "Sea Level",
    process: "Sun-Dried",
    stats: { acidity: 2, body: 4, sweetness: 5 , complexity: 4, finish: 4 },
    serve: {"vessel":"N/A","grind":"Whole","temp":"Room Temp","time":"Ready"}
  },
  // --- SPICES ---
  { 
    id: 16, 
    name: "True Ceylon Cinnamon", 
    category: "Spices", 
    basePrice: 15, 
    inStock: true,
    rating: 4.9, 
    notes: "Citrus, Floral, Sweet Wood",
    description: "Often called 'True Cinnamon', this Ceylon variety is vastly superior to common Cassia. It boasts a complex, delicate flavor profile with floral and citrus notes, and is low in coumarin. Perfect for dusting over cappuccinos or baking.",
    origin: "Sri Lanka",
    altitude: "500m",
    process: "Quilled",
    stats: { acidity: 3, body: 2, sweetness: 4 , complexity: 4, finish: 3 },
    serve: {"vessel":"Grinder/Zester","grind":"Freshly Ground","temp":"N/A","time":"Instant"}
  },
  { 
    id: 17, 
    name: "Tellicherry Black Pepper", 
    category: "Spices", 
    basePrice: 14, 
    inStock: true,
    rating: 4.8, 
    notes: "Pine, Citrus, Sharp Heat",
    description: "These extra-large peppercorns are left on the vine longer to develop a deep, complex flavor. They offer a robust, pine-like aroma and an intense, sharp heat that elevates any savory dish.",
    origin: "Malabar Coast, India",
    altitude: "Sea Level",
    process: "Sun-Dried",
    stats: { acidity: 4, body: 3, sweetness: 1 , complexity: 3, finish: 4 },
    serve: {"vessel":"Pepper Mill","grind":"Fresh Coarse","temp":"N/A","time":"Instant"}
  },
  { 
    id: 18, 
    name: "Kashmiri Saffron Sparks", 
    category: "Spices", 
    basePrice: 55, 
    inStock: true,
    rating: 5.0, 
    notes: "Hay, Honey, Metallic",
    description: "The most precious spice in the world. Our Kashmiri saffron features distinctively long, deep-red stigmas. Just a few threads will impart a brilliant golden hue and an incomparable, luxurious aroma to your culinary creations.",
    origin: "Pampore, Kashmir",
    altitude: "1,600m",
    process: "Hand-Picked",
    stats: { acidity: 1, body: 3, sweetness: 3 , complexity: 5, finish: 5 },
    serve: {"vessel":"Mortar & Pestle","grind":"Lightly Crushed","temp":"Warm Liquid","time":"5-10 Min Steep"}
  },
];

export const VARIANTS = [
  { weight: "100g", multiplier: 0.5 },
  { weight: "250g", multiplier: 1.0 },
  { weight: "500g", multiplier: 1.8 },
];
